### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by JourneyOver** [incace/NeuDark#1]
Hey just wondering on when you planned on uploading all the recent updates you have been doing to the style on up to us.o?

**Comment by colineberly** [comment]
I will get this up hopefully by the weekend. Everything is done, the only thing waiting is the new stylish popup menu. It's about 80% done at this point. Just trying to cover all the bases with possible scenarios. Thanks for the post and I will post back when updated.

**Comment by JourneyOver** [comment]
Sounds good :D Really loving the look of what you've changed (going by the screenshots) to stylus so far. Will look so much cleaner than it does with the current iteration of the style that is up on us.o

**Comment by colineberly** [comment]
The style has been updated. Check it out and if you find any bugs, post them. Thanks.
