### ISSUE TITLE
Misaligned Icons in popup.html

### ISSUE THREAD

**Issue by colineberly** [incace/NeuDark#2]
Icons are getting pushed to the right and cut off by the overflow when a style title is longer than the popup width and the text-overflow kicks in.

Screenshot of issue:
![](https://cloud.githubusercontent.com/assets/14100003/24575716/e36d1830-167b-11e7-9c24-e36ef10e9b1c.png)

**Comment by colineberly** [comment]
@narcolepticinsomniac this has been resolved and updated. Please check that it is fixed on your end. Thanks!

**Comment by narcolepticinsomniac** [comment]
Confirmed. Well done.

**Comment by colineberly** [comment]
Currently fucked up, re-opening as reminder.
