### ISSUE TITLE
Just a thought and the few things that are coming in the next release of stylus.

### ISSUE THREAD

**Issue by JourneyOver** [incace/NeuDark#4]
Since this [branch](https://github.com/schomery/stylish-chrome/tree/cm-and-cache) is pretty much feature complete now, all that's left is testing/reviewing/polishing with that being said I'm sure there are a slight few changes that may possibly come between now and the actual release of the next version, but I'd say it's probably a great idea to start working on the things that are broken so you have less people coming to cry about the style being half broken and stuff when the release hits.

One major change in the next version is that there is a new layout for the manage page (this is an optional feature and idk if there is any css shared between the old and new layout so might have to make an option on nuedark for people running the new layout or the old layout)

another I know for sure is that there are now .svg icons being used in certain places now that end up messing with the style in various ways. (happening on the old layout as well) and there are a few things that ended up getting unstyled as well.

**Comment by colineberly** [comment]
Thanks for this message. I'll start taking a look into it.

**Comment by JourneyOver** [comment]
@incace just to let you know the latest version of Stylus has been released to the chrome store now.
https://github.com/incace/NeuDark/issues/8 notes what issues are currently present with your style and the latest release.

**Comment by joshsleeper** [comment]
Funnily enough, I coincidentally had just installed Stylus and NeuDark for the very first time within a few hours of Stylus 1.0.6 being released.

That is to say that I'm super unfamiliar with the extension overall, and only called out what obviously looked wrong to me at a glance.
I wouldn't be surprised if there are other issues there that I didn't notice.

**Comment by JourneyOver** [comment]
@joshsleeper  you are fine, you pretty much hit everything that is currently messed up on the head for what needs to be fixed..
