### ISSUE TITLE
Don't know how to apply syntax themes

### ISSUE THREAD

**Issue by ghost** [incace/NeuDark#5]
![chrome_2017-04-08_18-13-51](https://cloud.githubusercontent.com/assets/21363469/24828012/22a9e47c-1c87-11e7-8fa6-4c6404fa4204.png)
Dropping a bug report as you requested. Default install gave me the incorrect text color. I read the description telling me to use the tommorow-night-bright syntax, but I don't know how.

**Comment by colineberly** [comment]
On your left side menu, scroll down. It should be an option just below tab size and keymap. Let me know if this helps. Also, I have the theme updates in the works currently and should all be fixed within a few days.

**Comment by ghost** [comment]
Found it. I wasn't aware that there were more options underneath the tickboxes. Maybe you should add a small note in the description just in case there are other people like me ><
