### ISSUE TITLE
Various Visual Issues on Stylus 1.0.6

### ISSUE THREAD

**Issue by joshsleeper** [incace/NeuDark#8]
* Google Chrome 58.0.3029.81 (64-bit)
* Stylus 1.0.6
* Latest NeuDark Release (Last Updated on us.o at time of writing: April 2, 2017)
---
## Confusing (duplicated?) buttons after styles
![image](https://cloud.githubusercontent.com/assets/849941/25643583/6fda276c-2f55-11e7-9fde-cd60174e084c.png)

## Misaligned buttons in "Installed Styles" sidebar 
![image](https://cloud.githubusercontent.com/assets/849941/25643443/aa205de8-2f54-11e7-8f5d-2f1387a2e90a.png)

## Various issues in "Edit Style" sidebar
![image](https://cloud.githubusercontent.com/assets/849941/25643676/b9b7d028-2f55-11e7-8a4a-a12aecbe8c93.png)

## New manage UI layout is all sorts of goofy
![image](https://cloud.githubusercontent.com/assets/849941/25643529/37d13888-2f55-11e7-9699-bf596e30c588.png)

**Comment by colineberly** [comment]
Thanks for this with the screenshots. I'll start on it.

**Comment by JourneyOver** [comment]
@incace just checking in, any word on when an update will be coming for this style?

**Comment by colineberly** [comment]
I am starting on it this weekend. I've been in the middle of a full version update of my Workflowy theme and wanted to get that sorted first so that I wouldn't lose track of things I wanted to change. Don't worry I use lists, but it's easier for me to just focus on one thing at a time and get it done otherwise everything will be in a constant "in progress" limbo and nothing ever gets finished.

**Comment by JourneyOver** [comment]
ah it's all good man, know how that is since I always get caught up in trying to do to many things and never getting anything done even if I want to only focus on working on one thing at a time >.<

**Comment by joshsleeper** [comment]
This issue persists in Stylus 1.0.8
No pressure to rush anything (I totally know the pain of multitasking too much), just an FYI.

**Comment by cucumbur** [comment]
Can confirm I have all these issues as well. thanks for maintaining

**Comment by joshsleeper** [comment]
Stylus 1.1.0 was just released and all issues seem to remain.

Not prodding, just informing that the issues reported above are all still valid.

Thanks again for all your hard work!

**Comment by colineberly** [comment]
Hey everyone, I know I have been pretty MIA with this as I have had less dev work lately and more focus on design/print work. I haven't been on the code end much lately, but am starting back up on this tonight. I'll go through as quickly as possible with all the issues regarding **Stylus** and figure out simple yet effective fixes. I'm not going to tweak out too hard on it.

On another note, which I'm sure none of you even are worried about at this point, but I don't have any plans on tweaking anything on the **Stylish** side at the moment. I run both extensions, but there's too many issues with the dropdown constantly changing that dev is currently "on hold" for the time being.

Thank you guys @joshsleeper @JourneyOver for taking the time to put the issues together for me and everyone for being so patient.

**Comment by JourneyOver** [comment]
Sounds great! :D I've been missing this style lately as it's one of my most faves for Stylus. 

I don't blame you on not wanting to tweak or update anything on the stylish side of things, things have been such a mess with both the stylish extension and the website ever since those new devs (can we even call them devs at this point? lol they have shown they are so incompetent with both the site and extension + have disappeared off the face of the planet in the past 2/3 months) took over. Honestly can't wait for someone to come along and make a new userstyle site, I'd jump as quickly as I could xD

**Comment by joshsleeper** [comment]
Nah, thank you @incace for creating and maintaining this to begin with! ;)
I'm a QA Engineer at work anyway, so good bug reports come naturally~

Looking forward to those fixes!

**Comment by joshsleeper** [comment]
@incace 
The politest bump. ;)
No pressure, just keeping this on your radar.

**Comment by colineberly** [comment]
Just wanted to post an update guys. I'm tackling this and currently have finished the sidebar on manage page for both old and new UI. Here is a screenshot:

![sidebar](https://user-images.githubusercontent.com/61343/31005440-e7329c42-a4b5-11e7-8b95-fc7a25f8a0cc.png)

Next, I will fix any issues with the old UI on main manage list area (only a couple) and then update the same area for the new UI (more issues). After that, moving to the edit page which only has a couple problems, mainly sidebar stuff.

**Comment by JourneyOver** [comment]
Looking good so far ^^

**Comment by joshsleeper** [comment]
@incace Looking great! Thanks so much!

**Comment by colineberly** [comment]
Quick question for you guys. A while back, when it was just Stylish dedicated, I started writing in some responsive styles and had planned on having minimum 2 breakpoints. Me personally, I only use it on desktop at 1920 so I really have no use for it for smaller devices, but the idea was to have it scale for half-screen use and then for fullscreen use. That way if you do some side-by-side setups, it will fit properly. For instance, currently I have my main browser window on my right monitor, then I have devtools open on left monitor half-screen and the other half of the left monitor is my Stylus window.

Anyway, I guess my question is, do you guys care about having responsive functionality under a half-screen desktop setup?

**Comment by JourneyOver** [comment]
For myself personally it's whatever, you can add it if you want or not add it if you don't want to, as I rarely if ever have the stylus editor open and the dev tools open at the same time in the same tab.

**Comment by joshsleeper** [comment]
I think it's a "nice to have" more than a "required" thing for sure.

If it matters, I exclusively use my browser on a 1920x1080p monitor rotated in a portrait orientation (so I guess 1080x1920p, since it's rotated.), so technically I'm always running responsive things in a more portrait/mobile format.

**Comment by colineberly** [comment]
Thanks for the input. What I've decided to do for the time being is just get the standard desktop version updated with all issues fixed then I'll dive back into the responsive vision I had after the fact.

**Comment by Zerophase** [comment]
Does version 2.6 fix these issues? Any news on when the new version is going up on userstyles?

**Comment by colineberly** [comment]
In the process of ironing out all visual bugs from before. Will update on status of next release. Back at it.
